# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\workspace\tools\tools.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(1200, 700)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(1200, 700))
        Form.setMaximumSize(QtCore.QSize(1200, 700))
        font = QtGui.QFont()
        font.setPointSize(13)
        Form.setFont(font)
        Form.setToolTip("")
        Form.setToolTipDuration(-1)
        Form.setStatusTip("")
        Form.setLayoutDirection(QtCore.Qt.LeftToRight)
        Form.setAutoFillBackground(True)
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 90, 1201, 651))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.page_1)
        self.stackedWidget_2.setGeometry(QtCore.QRect(0, 40, 1201, 631))
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.s2_page_1 = QtWidgets.QWidget()
        self.s2_page_1.setObjectName("s2_page_1")
        self.s2_p1_b2 = QtWidgets.QPushButton(self.s2_page_1)
        self.s2_p1_b2.setGeometry(QtCore.QRect(520, 380, 141, 41))
        self.s2_p1_b2.setObjectName("s2_p1_b2")
        self.s2_p1_b1 = QtWidgets.QPushButton(self.s2_page_1)
        self.s2_p1_b1.setGeometry(QtCore.QRect(520, 170, 141, 41))
        self.s2_p1_b1.setObjectName("s2_p1_b1")
        self.s2_p1_t1 = QtWidgets.QTextEdit(self.s2_page_1)
        self.s2_p1_t1.setGeometry(QtCore.QRect(0, 100, 521, 401))
        self.s2_p1_t1.setObjectName("s2_p1_t1")
        self.s2_p1_t2 = QtWidgets.QTextEdit(self.s2_page_1)
        self.s2_p1_t2.setGeometry(QtCore.QRect(660, 100, 531, 401))
        self.s2_p1_t2.setObjectName("s2_p1_t2")
        self.s2_p1_b2.raise_()
        self.s2_p1_t2.raise_()
        self.s2_p1_b1.raise_()
        self.s2_p1_t1.raise_()
        self.s2_p1_t2.raise_()
        self.stackedWidget_2.addWidget(self.s2_page_1)
        self.s2_page_2 = QtWidgets.QWidget()
        self.s2_page_2.setObjectName("s2_page_2")
        self.s2_p2_b1 = QtWidgets.QPushButton(self.s2_page_2)
        self.s2_p2_b1.setGeometry(QtCore.QRect(520, 170, 141, 41))
        self.s2_p2_b1.setObjectName("s2_p2_b1")
        self.s2_p2_t2 = QtWidgets.QTextEdit(self.s2_page_2)
        self.s2_p2_t2.setGeometry(QtCore.QRect(660, 100, 531, 401))
        self.s2_p2_t2.setObjectName("s2_p2_t2")
        self.s2_p2_b2 = QtWidgets.QPushButton(self.s2_page_2)
        self.s2_p2_b2.setGeometry(QtCore.QRect(520, 380, 141, 41))
        self.s2_p2_b2.setObjectName("s2_p2_b2")
        self.s2_p2_t1 = QtWidgets.QTextEdit(self.s2_page_2)
        self.s2_p2_t1.setGeometry(QtCore.QRect(0, 100, 521, 401))
        self.s2_p2_t1.setObjectName("s2_p2_t1")
        self.stackedWidget_2.addWidget(self.s2_page_2)
        self.s2_page_3 = QtWidgets.QWidget()
        self.s2_page_3.setObjectName("s2_page_3")
        self.s2_p3_b1 = QtWidgets.QPushButton(self.s2_page_3)
        self.s2_p3_b1.setGeometry(QtCore.QRect(520, 170, 141, 41))
        self.s2_p3_b1.setObjectName("s2_p3_b1")
        self.s2_p3_t2 = QtWidgets.QTextEdit(self.s2_page_3)
        self.s2_p3_t2.setGeometry(QtCore.QRect(660, 100, 531, 401))
        self.s2_p3_t2.setObjectName("s2_p3_t2")
        self.s2_p3_b2 = QtWidgets.QPushButton(self.s2_page_3)
        self.s2_p3_b2.setGeometry(QtCore.QRect(520, 380, 141, 41))
        self.s2_p3_b2.setObjectName("s2_p3_b2")
        self.s2_p3_t1 = QtWidgets.QTextEdit(self.s2_page_3)
        self.s2_p3_t1.setGeometry(QtCore.QRect(0, 100, 521, 401))
        self.s2_p3_t1.setObjectName("s2_p3_t1")
        self.stackedWidget_2.addWidget(self.s2_page_3)
        self.code = QtWidgets.QComboBox(self.page_1)
        self.code.setGeometry(QtCore.QRect(0, 0, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.code.setFont(font)
        self.code.setEditable(False)
        self.code.setObjectName("code")
        self.code.addItem("")
        self.code.addItem("")
        self.code.addItem("")
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.tabWidget = QtWidgets.QTabWidget(self.page_2)
        self.tabWidget.setGeometry(QtCore.QRect(0, 10, 1191, 641))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.webView_1 = QtWebKitWidgets.QWebView(self.tab_1)
        self.webView_1.setGeometry(QtCore.QRect(0, 0, 1191, 641))
        self.webView_1.setUrl(QtCore.QUrl("about:blank"))
        self.webView_1.setObjectName("webView_1")
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.webView_2 = QtWebKitWidgets.QWebView(self.tab_2)
        self.webView_2.setGeometry(QtCore.QRect(-1, -1, 1191, 641))
        self.webView_2.setUrl(QtCore.QUrl("about:blank"))
        self.webView_2.setObjectName("webView_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.webView_3 = QtWebKitWidgets.QWebView(self.tab_3)
        self.webView_3.setGeometry(QtCore.QRect(-1, -1, 1191, 641))
        self.webView_3.setUrl(QtCore.QUrl("about:blank"))
        self.webView_3.setObjectName("webView_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.p3_l1 = QtWidgets.QLineEdit(self.page_3)
        self.p3_l1.setGeometry(QtCore.QRect(0, 10, 1191, 41))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.p3_l1.setFont(font)
        self.p3_l1.setObjectName("p3_l1")
        self.p3_b1 = QtWidgets.QPushButton(self.page_3)
        self.p3_b1.setGeometry(QtCore.QRect(0, 70, 111, 41))
        self.p3_b1.setObjectName("p3_b1")
        self.p3_t1 = QtWidgets.QTextEdit(self.page_3)
        self.p3_t1.setGeometry(QtCore.QRect(121, 60, 256, 591))
        self.p3_t1.setObjectName("p3_t1")
        self.p3_w1 = QtWebKitWidgets.QWebView(self.page_3)
        self.p3_w1.setGeometry(QtCore.QRect(383, 60, 811, 611))
        self.p3_w1.setUrl(QtCore.QUrl("about:blank"))
        self.p3_w1.setObjectName("p3_w1")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.stackedWidget_3 = QtWidgets.QStackedWidget(self.page_4)
        self.stackedWidget_3.setGeometry(QtCore.QRect(0, 9, 1201, 601))
        self.stackedWidget_3.setObjectName("stackedWidget_3")
        self.s3_page_1 = QtWidgets.QWidget()
        self.s3_page_1.setObjectName("s3_page_1")
        self.s3_p1_e16 = QtWidgets.QLineEdit(self.s3_page_1)
        self.s3_p1_e16.setGeometry(QtCore.QRect(430, 540, 141, 31))
        self.s3_p1_e16.setObjectName("s3_p1_e16")
        self.s3_p1_e9 = QtWidgets.QLineEdit(self.s3_page_1)
        self.s3_p1_e9.setGeometry(QtCore.QRect(430, 50, 141, 31))
        self.s3_p1_e9.setObjectName("s3_p1_e9")
        self.s3_p1_e12 = QtWidgets.QLineEdit(self.s3_page_1)
        self.s3_p1_e12.setGeometry(QtCore.QRect(430, 260, 141, 31))
        self.s3_p1_e12.setObjectName("s3_p1_e12")
        self.s3_p1_e6 = QtWidgets.QLineEdit(self.s3_page_1)
        self.s3_p1_e6.setGeometry(QtCore.QRect(110, 400, 141, 31))
        self.s3_p1_e6.setObjectName("s3_p1_e6")
        self.s3_p1_e21 = QtWidgets.QLineEdit(self.s3_page_1)
        self.s3_p1_e21.setGeometry(QtCore.QRect(740, 330, 141, 31))
        self.s3_p1_e21.setObjectName("s3_p1_e21")
        self.s3_p1_e5 = QtWidgets.QLineEdit(self.s3_page_1)
        self.s3_p1_e5.setGeometry(QtCore.QRect(110, 330, 141, 31))
        self.s3_p1_e5.setObjectName("s3_p1_e5")
        self.s3_p1_e20 = QtWidgets.QLineEdit(self.s3_page_1)
        self.s3_p1_e20.setGeometry(QtCore.QRect(740, 260, 141, 31))
        self.s3_p1_e20.setObjectName("s3_p1_e20")
        self.s3_p1_l5 = QtWidgets.QLabel(self.s3_page_1)
        self.s3_p1_l5.setGeometry(QtCore.QRect(20, 330, 91, 31))
        self.s3_p1_l5.setObjectName("s3_p1_l5")
        self.s3_p1_e8 = QtWidgets.QLineEdit(self.s3_page_1)
        self.s3_p1_e8.setGeometry(QtCore.QRect(110, 540, 141, 31))
        self.s3_p1_e8.setObjectName("s3_p1_e8")
        self.s3_p1_l9 = QtWidgets.QLabel(self.s3_page_1)
        self.s3_p1_l9.setGeometry(QtCore.QRect(340, 50, 91, 31))
        self.s3_p1_l9.setObjectName("s3_p1_l9")
        self.s3_p1_l15 = QtWidgets.QLabel(self.s3_page_1)
        self.s3_p1_l15.setGeometry(QtCore.QRect(340, 470, 91, 31))
        self.s3_p1_l15.setObjectName("s3_p1_l15")
        self.s3_p1_l2 = QtWidgets.QLabel(self.s3_page_1)
        self.s3_p1_l2.setGeometry(QtCore.QRect(20, 120, 91, 31))
        self.s3_p1_l2.setObjectName("s3_p1_l2")
        self.s3_p1_l13 = QtWidgets.QLabel(self.s3_page_1)
        self.s3_p1_l13.setGeometry(QtCore.QRect(340, 330, 91, 31))
        self.s3_p1_l13.setObjectName("s3_p1_l13")
        self.s3_p1_l16 = QtWidgets.QLabel(self.s3_page_1)
        self.s3_p1_l16.setGeometry(QtCore.QRect(340, 540, 91, 31))
        self.s3_p1_l16.setObjectName("s3_p1_l16")
        self.s3_p1_e4 = QtWidgets.QLineEdit(self.s3_page_1)
        self.s3_p1_e4.setGeometry(QtCore.QRect(110, 260, 141, 31))
        self.s3_p1_e4.setObjectName("s3_p1_e4")
        self.s3_p1_l14 = QtWidgets.QLabel(self.s3_page_1)
        self.s3_p1_l14.setGeometry(QtCore.QRect(340, 400, 91, 31))
        self.s3_p1_l14.setObjectName("s3_p1_l14")
        self.s3_p1_b1 = QtWidgets.QPushButton(self.s3_page_1)
        self.s3_p1_b1.setGeometry(QtCore.QRect(990, 480, 111, 41))
        self.s3_p1_b1.setObjectName("s3_p1_b1")
        self.s3_p1_l7 = QtWidgets.QLabel(self.s3_page_1)
        self.s3_p1_l7.setGeometry(QtCore.QRect(20, 470, 91, 31))
        self.s3_p1_l7.setObjectName("s3_p1_l7")
        self.s3_p1_e14 = QtWidgets.QLineEdit(self.s3_page_1)
        self.s3_p1_e14.setGeometry(QtCore.QRect(430, 400, 141, 31))
        self.s3_p1_e14.setObjectName("s3_p1_e14")
        self.s3_p1_l10 = QtWidgets.QLabel(self.s3_page_1)
        self.s3_p1_l10.setGeometry(QtCore.QRect(340, 120, 91, 31))
        self.s3_p1_l10.setObjectName("s3_p1_l10")
        self.s3_p1_l12 = QtWidgets.QLabel(self.s3_page_1)
        self.s3_p1_l12.setGeometry(QtCore.QRect(340, 260, 91, 31))
        self.s3_p1_l12.setObjectName("s3_p1_l12")
        self.s3_p1_e17 = QtWidgets.QLineEdit(self.s3_page_1)
        self.s3_p1_e17.setGeometry(QtCore.QRect(740, 50, 141, 31))
        self.s3_p1_e17.setObjectName("s3_p1_e17")
        self.s3_p1_e2 = QtWidgets.QLineEdit(self.s3_page_1)
        self.s3_p1_e2.setGeometry(QtCore.QRect(110, 120, 141, 31))
        self.s3_p1_e2.setObjectName("s3_p1_e2")
        self.s3_p1_e18 = QtWidgets.QLineEdit(self.s3_page_1)
        self.s3_p1_e18.setGeometry(QtCore.QRect(740, 120, 141, 31))
        self.s3_p1_e18.setObjectName("s3_p1_e18")
        self.s3_p1_l1 = QtWidgets.QLabel(self.s3_page_1)
        self.s3_p1_l1.setGeometry(QtCore.QRect(20, 50, 91, 31))
        self.s3_p1_l1.setObjectName("s3_p1_l1")
        self.s3_p1_l24 = QtWidgets.QLabel(self.s3_page_1)
        self.s3_p1_l24.setGeometry(QtCore.QRect(650, 540, 91, 31))
        self.s3_p1_l24.setObjectName("s3_p1_l24")
        self.s3_p1_l21 = QtWidgets.QLabel(self.s3_page_1)
        self.s3_p1_l21.setGeometry(QtCore.QRect(650, 330, 91, 31))
        self.s3_p1_l21.setObjectName("s3_p1_l21")
        self.s3_p1_e22 = QtWidgets.QLineEdit(self.s3_page_1)
        self.s3_p1_e22.setGeometry(QtCore.QRect(740, 400, 141, 31))
        self.s3_p1_e22.setObjectName("s3_p1_e22")
        self.s3_p1_l22 = QtWidgets.QLabel(self.s3_page_1)
        self.s3_p1_l22.setGeometry(QtCore.QRect(650, 400, 91, 31))
        self.s3_p1_l22.setObjectName("s3_p1_l22")
        self.s3_p1_l6 = QtWidgets.QLabel(self.s3_page_1)
        self.s3_p1_l6.setGeometry(QtCore.QRect(20, 400, 91, 31))
        self.s3_p1_l6.setObjectName("s3_p1_l6")
        self.s3_p1_e10 = QtWidgets.QLineEdit(self.s3_page_1)
        self.s3_p1_e10.setGeometry(QtCore.QRect(430, 120, 141, 31))
        self.s3_p1_e10.setObjectName("s3_p1_e10")
        self.s3_p1_e1 = QtWidgets.QLineEdit(self.s3_page_1)
        self.s3_p1_e1.setGeometry(QtCore.QRect(110, 50, 141, 31))
        self.s3_p1_e1.setObjectName("s3_p1_e1")
        self.s3_p1_l23 = QtWidgets.QLabel(self.s3_page_1)
        self.s3_p1_l23.setGeometry(QtCore.QRect(650, 470, 91, 31))
        self.s3_p1_l23.setObjectName("s3_p1_l23")
        self.s3_p1_e13 = QtWidgets.QLineEdit(self.s3_page_1)
        self.s3_p1_e13.setGeometry(QtCore.QRect(430, 330, 141, 31))
        self.s3_p1_e13.setObjectName("s3_p1_e13")
        self.s3_p1_l17 = QtWidgets.QLabel(self.s3_page_1)
        self.s3_p1_l17.setGeometry(QtCore.QRect(650, 50, 91, 31))
        self.s3_p1_l17.setObjectName("s3_p1_l17")
        self.s3_p1_l11 = QtWidgets.QLabel(self.s3_page_1)
        self.s3_p1_l11.setGeometry(QtCore.QRect(340, 190, 91, 31))
        self.s3_p1_l11.setObjectName("s3_p1_l11")
        self.s3_p1_e24 = QtWidgets.QLineEdit(self.s3_page_1)
        self.s3_p1_e24.setGeometry(QtCore.QRect(740, 540, 141, 31))
        self.s3_p1_e24.setObjectName("s3_p1_e24")
        self.s3_p1_c1 = QtWidgets.QCheckBox(self.s3_page_1)
        self.s3_p1_c1.setGeometry(QtCore.QRect(970, 370, 141, 31))
        self.s3_p1_c1.setObjectName("s3_p1_c1")
        self.s3_p1_l20 = QtWidgets.QLabel(self.s3_page_1)
        self.s3_p1_l20.setGeometry(QtCore.QRect(650, 260, 91, 31))
        self.s3_p1_l20.setObjectName("s3_p1_l20")
        self.s3_p1_l19 = QtWidgets.QLabel(self.s3_page_1)
        self.s3_p1_l19.setGeometry(QtCore.QRect(650, 190, 91, 31))
        self.s3_p1_l19.setObjectName("s3_p1_l19")
        self.s3_p1_e11 = QtWidgets.QLineEdit(self.s3_page_1)
        self.s3_p1_e11.setGeometry(QtCore.QRect(430, 190, 141, 31))
        self.s3_p1_e11.setObjectName("s3_p1_e11")
        self.s3_p1_l3 = QtWidgets.QLabel(self.s3_page_1)
        self.s3_p1_l3.setGeometry(QtCore.QRect(20, 190, 91, 31))
        self.s3_p1_l3.setObjectName("s3_p1_l3")
        self.s3_p1_l8 = QtWidgets.QLabel(self.s3_page_1)
        self.s3_p1_l8.setGeometry(QtCore.QRect(20, 540, 91, 31))
        self.s3_p1_l8.setObjectName("s3_p1_l8")
        self.s3_p1_l4 = QtWidgets.QLabel(self.s3_page_1)
        self.s3_p1_l4.setGeometry(QtCore.QRect(20, 260, 91, 31))
        self.s3_p1_l4.setObjectName("s3_p1_l4")
        self.s3_p1_l18 = QtWidgets.QLabel(self.s3_page_1)
        self.s3_p1_l18.setGeometry(QtCore.QRect(650, 120, 91, 31))
        self.s3_p1_l18.setObjectName("s3_p1_l18")
        self.s3_p1_e7 = QtWidgets.QLineEdit(self.s3_page_1)
        self.s3_p1_e7.setGeometry(QtCore.QRect(110, 470, 141, 31))
        self.s3_p1_e7.setObjectName("s3_p1_e7")
        self.s3_p1_d1 = QtWidgets.QDateEdit(self.s3_page_1)
        self.s3_p1_d1.setGeometry(QtCore.QRect(110, 190, 141, 31))
        self.s3_p1_d1.setObjectName("s3_p1_d1")
        self.s3_p1_ed3 = QtWidgets.QDateEdit(self.s3_page_1)
        self.s3_p1_ed3.setGeometry(QtCore.QRect(740, 190, 141, 31))
        self.s3_p1_ed3.setObjectName("s3_p1_ed3")
        self.s3_p1_d4 = QtWidgets.QDateEdit(self.s3_page_1)
        self.s3_p1_d4.setGeometry(QtCore.QRect(740, 470, 141, 31))
        self.s3_p1_d4.setObjectName("s3_p1_d4")
        self.s3_p1_d2 = QtWidgets.QDateEdit(self.s3_page_1)
        self.s3_p1_d2.setGeometry(QtCore.QRect(430, 470, 141, 31))
        self.s3_p1_d2.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(0, 0, 0)))
        self.s3_p1_d2.setTime(QtCore.QTime(0, 0, 0))
        self.s3_p1_d2.setObjectName("s3_p1_d2")
        self.widget = QtWidgets.QWidget(self.s3_page_1)
        self.widget.setGeometry(QtCore.QRect(908, 90, 116, 181))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.s3_p1_r1 = QtWidgets.QRadioButton(self.widget)
        self.s3_p1_r1.setChecked(True)
        self.s3_p1_r1.setObjectName("s3_p1_r1")
        self.verticalLayout.addWidget(self.s3_p1_r1)
        self.s3_p1_r2 = QtWidgets.QRadioButton(self.widget)
        self.s3_p1_r2.setChecked(False)
        self.s3_p1_r2.setObjectName("s3_p1_r2")
        self.verticalLayout.addWidget(self.s3_p1_r2)
        self.s3_p1_r3 = QtWidgets.QRadioButton(self.widget)
        self.s3_p1_r3.setObjectName("s3_p1_r3")
        self.verticalLayout.addWidget(self.s3_p1_r3)
        self.s3_p1_r4 = QtWidgets.QRadioButton(self.widget)
        self.s3_p1_r4.setObjectName("s3_p1_r4")
        self.verticalLayout.addWidget(self.s3_p1_r4)
        self.widget1 = QtWidgets.QWidget(self.s3_page_1)
        self.widget1.setGeometry(QtCore.QRect(1028, 90, 154, 181))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.s3_p1_r5 = QtWidgets.QRadioButton(self.widget1)
        self.s3_p1_r5.setChecked(True)
        self.s3_p1_r5.setObjectName("s3_p1_r5")
        self.verticalLayout_2.addWidget(self.s3_p1_r5)
        self.s3_p1_r6 = QtWidgets.QRadioButton(self.widget1)
        self.s3_p1_r6.setObjectName("s3_p1_r6")
        self.verticalLayout_2.addWidget(self.s3_p1_r6)
        self.s3_p1_r7 = QtWidgets.QRadioButton(self.widget1)
        self.s3_p1_r7.setObjectName("s3_p1_r7")
        self.verticalLayout_2.addWidget(self.s3_p1_r7)
        self.s3_p1_r8 = QtWidgets.QRadioButton(self.widget1)
        self.s3_p1_r8.setObjectName("s3_p1_r8")
        self.verticalLayout_2.addWidget(self.s3_p1_r8)
        self.stackedWidget_3.addWidget(self.s3_page_1)
        self.s3_page_2 = QtWidgets.QWidget()
        self.s3_page_2.setObjectName("s3_page_2")
        self.s3_p2_b1 = QtWidgets.QPushButton(self.s3_page_2)
        self.s3_p2_b1.setGeometry(QtCore.QRect(990, 480, 111, 51))
        self.s3_p2_b1.setObjectName("s3_p2_b1")
        self.s3_p2_t1 = QtWidgets.QTextEdit(self.s3_page_2)
        self.s3_p2_t1.setGeometry(QtCore.QRect(40, 10, 821, 581))
        self.s3_p2_t1.setObjectName("s3_p2_t1")
        self.stackedWidget_3.addWidget(self.s3_page_2)
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.stackedWidget.addWidget(self.page_6)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.stackedWidget.addWidget(self.page_7)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.stackedWidget.addWidget(self.page_8)
        self.b1 = QtWidgets.QPushButton(Form)
        self.b1.setGeometry(QtCore.QRect(0, 0, 111, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b1.sizePolicy().hasHeightForWidth())
        self.b1.setSizePolicy(sizePolicy)
        self.b1.setObjectName("b1")
        self.b2 = QtWidgets.QPushButton(Form)
        self.b2.setGeometry(QtCore.QRect(110, 0, 111, 41))
        self.b2.setObjectName("b2")
        self.b3 = QtWidgets.QPushButton(Form)
        self.b3.setGeometry(QtCore.QRect(220, 0, 111, 41))
        self.b3.setObjectName("b3")
        self.b4 = QtWidgets.QPushButton(Form)
        self.b4.setGeometry(QtCore.QRect(330, 0, 111, 41))
        self.b4.setObjectName("b4")
        self.b5 = QtWidgets.QPushButton(Form)
        self.b5.setGeometry(QtCore.QRect(440, 0, 111, 41))
        self.b5.setObjectName("b5")
        self.b6 = QtWidgets.QPushButton(Form)
        self.b6.setGeometry(QtCore.QRect(550, 0, 111, 41))
        self.b6.setObjectName("b6")
        self.b7 = QtWidgets.QPushButton(Form)
        self.b7.setGeometry(QtCore.QRect(660, 0, 111, 41))
        self.b7.setObjectName("b7")
        self.b8 = QtWidgets.QPushButton(Form)
        self.b8.setGeometry(QtCore.QRect(760, 0, 111, 41))
        self.b8.setObjectName("b8")

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(3)
        self.stackedWidget_2.setCurrentIndex(2)
        self.code.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Tools"))
        self.s2_p1_b2.setText(_translate("Form", "urldecode"))
        self.s2_p1_b1.setText(_translate("Form", "urlencode"))
        self.s2_p1_t1.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'宋体\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.s2_p2_b1.setText(_translate("Form", "base64encode"))
        self.s2_p2_b2.setText(_translate("Form", "base64decode"))
        self.s2_p2_t1.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'宋体\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.s2_p3_b1.setText(_translate("Form", "hexencode"))
        self.s2_p3_b2.setText(_translate("Form", "hexdecode"))
        self.s2_p3_t1.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'宋体\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.code.setCurrentText(_translate("Form", "url"))
        self.code.setItemText(0, _translate("Form", "url"))
        self.code.setItemText(1, _translate("Form", "base64"))
        self.code.setItemText(2, _translate("Form", "hex"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("Form", "www.aizhan.com"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "tool.chinaz.com"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "www.alexa.cn"))
        self.p3_l1.setText(_translate("Form", "INPUT HASH HERE"))
        self.p3_b1.setText(_translate("Form", "check"))
        self.s3_p1_l5.setText(_translate("Form", "qq"))
        self.s3_p1_l9.setText(_translate("Form", "密码1"))
        self.s3_p1_l15.setText(_translate("Form", "配偶出生日期"))
        self.s3_p1_l2.setText(_translate("Form", "姓名简拼"))
        self.s3_p1_l13.setText(_translate("Form", "配偶姓名全拼"))
        self.s3_p1_l16.setText(_translate("Form", "配偶手机"))
        self.s3_p1_l14.setText(_translate("Form", "配偶姓名简拼"))
        self.s3_p1_b1.setText(_translate("Form", "Try Your Luck"))
        self.s3_p1_l7.setText(_translate("Form", "用户名1"))
        self.s3_p1_l10.setText(_translate("Form", "密码2"))
        self.s3_p1_l12.setText(_translate("Form", "补充2"))
        self.s3_p1_l1.setText(_translate("Form", "姓名全拼"))
        self.s3_p1_l24.setText(_translate("Form", "父亲手机"))
        self.s3_p1_l21.setText(_translate("Form", "父亲姓名全拼"))
        self.s3_p1_l22.setText(_translate("Form", "父亲姓名简拼"))
        self.s3_p1_l6.setText(_translate("Form", "曾用qq"))
        self.s3_p1_l23.setText(_translate("Form", "父亲出生日期"))
        self.s3_p1_l17.setText(_translate("Form", "母亲姓名全拼"))
        self.s3_p1_l11.setText(_translate("Form", "补充1"))
        self.s3_p1_c1.setText(_translate("Form", "包含额为特殊字符"))
        self.s3_p1_l20.setText(_translate("Form", "母亲手机"))
        self.s3_p1_l19.setText(_translate("Form", "母亲出生日期"))
        self.s3_p1_l3.setText(_translate("Form", "出生日期"))
        self.s3_p1_l8.setText(_translate("Form", "用户名2"))
        self.s3_p1_l4.setText(_translate("Form", "手机"))
        self.s3_p1_l18.setText(_translate("Form", "母亲姓名简拼"))
        self.s3_p1_r1.setText(_translate("Form", "6位密码"))
        self.s3_p1_r2.setText(_translate("Form", "8位密码"))
        self.s3_p1_r3.setText(_translate("Form", "7-11位密码"))
        self.s3_p1_r4.setText(_translate("Form", "12-16位密码"))
        self.s3_p1_r5.setText(_translate("Form", "30次随机组合"))
        self.s3_p1_r6.setText(_translate("Form", "100次随机组合"))
        self.s3_p1_r7.setText(_translate("Form", "200次随机组合"))
        self.s3_p1_r8.setText(_translate("Form", "600次随机组合"))
        self.s3_p2_b1.setText(_translate("Form", "go back"))
        self.b1.setText(_translate("Form", "(en|de)code"))
        self.b2.setText(_translate("Form", "toolsites"))
        self.b3.setText(_translate("Form", "decrypt"))
        self.b4.setText(_translate("Form", "secret"))
        self.b5.setText(_translate("Form", "5"))
        self.b6.setText(_translate("Form", "6"))
        self.b7.setText(_translate("Form", "7"))
        self.b8.setText(_translate("Form", "8"))

from PyQt5 import QtWebKitWidgets

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

