# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\workspace\tools\tools.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(1200, 700)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(1200, 700))
        Form.setMaximumSize(QtCore.QSize(1200, 700))
        font = QtGui.QFont()
        font.setPointSize(13)
        Form.setFont(font)
        Form.setToolTip("")
        Form.setToolTipDuration(-1)
        Form.setStatusTip("")
        Form.setLayoutDirection(QtCore.Qt.LeftToRight)
        Form.setAutoFillBackground(True)
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 50, 1201, 651))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.page_1)
        self.stackedWidget_2.setGeometry(QtCore.QRect(0, 40, 1201, 631))
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.s2_page_1 = QtWidgets.QWidget()
        self.s2_page_1.setObjectName("s2_page_1")
        self.s2_p1_b2 = QtWidgets.QPushButton(self.s2_page_1)
        self.s2_p1_b2.setGeometry(QtCore.QRect(520, 380, 141, 41))
        self.s2_p1_b2.setObjectName("s2_p1_b2")
        self.s2_p1_b1 = QtWidgets.QPushButton(self.s2_page_1)
        self.s2_p1_b1.setGeometry(QtCore.QRect(520, 170, 141, 41))
        self.s2_p1_b1.setObjectName("s2_p1_b1")
        self.s2_p1_t1 = QtWidgets.QTextEdit(self.s2_page_1)
        self.s2_p1_t1.setGeometry(QtCore.QRect(0, 100, 521, 401))
        self.s2_p1_t1.setObjectName("s2_p1_t1")
        self.s2_p1_t2 = QtWidgets.QTextEdit(self.s2_page_1)
        self.s2_p1_t2.setGeometry(QtCore.QRect(660, 100, 531, 401))
        self.s2_p1_t2.setObjectName("s2_p1_t2")
        self.s2_p1_b2.raise_()
        self.s2_p1_t2.raise_()
        self.s2_p1_b1.raise_()
        self.s2_p1_t1.raise_()
        self.s2_p1_t2.raise_()
        self.stackedWidget_2.addWidget(self.s2_page_1)
        self.s2_page_2 = QtWidgets.QWidget()
        self.s2_page_2.setObjectName("s2_page_2")
        self.s2_p2_b1 = QtWidgets.QPushButton(self.s2_page_2)
        self.s2_p2_b1.setGeometry(QtCore.QRect(520, 170, 141, 41))
        self.s2_p2_b1.setObjectName("s2_p2_b1")
        self.s2_p2_t2 = QtWidgets.QTextEdit(self.s2_page_2)
        self.s2_p2_t2.setGeometry(QtCore.QRect(660, 100, 531, 401))
        self.s2_p2_t2.setObjectName("s2_p2_t2")
        self.s2_p2_b2 = QtWidgets.QPushButton(self.s2_page_2)
        self.s2_p2_b2.setGeometry(QtCore.QRect(520, 380, 141, 41))
        self.s2_p2_b2.setObjectName("s2_p2_b2")
        self.s2_p2_t1 = QtWidgets.QTextEdit(self.s2_page_2)
        self.s2_p2_t1.setGeometry(QtCore.QRect(0, 100, 521, 401))
        self.s2_p2_t1.setObjectName("s2_p2_t1")
        self.stackedWidget_2.addWidget(self.s2_page_2)
        self.s2_page_3 = QtWidgets.QWidget()
        self.s2_page_3.setObjectName("s2_page_3")
        self.s2_p3_b1 = QtWidgets.QPushButton(self.s2_page_3)
        self.s2_p3_b1.setGeometry(QtCore.QRect(520, 170, 141, 41))
        self.s2_p3_b1.setObjectName("s2_p3_b1")
        self.s2_p3_t2 = QtWidgets.QTextEdit(self.s2_page_3)
        self.s2_p3_t2.setGeometry(QtCore.QRect(660, 100, 531, 401))
        self.s2_p3_t2.setObjectName("s2_p3_t2")
        self.s2_p3_b2 = QtWidgets.QPushButton(self.s2_page_3)
        self.s2_p3_b2.setGeometry(QtCore.QRect(520, 380, 141, 41))
        self.s2_p3_b2.setObjectName("s2_p3_b2")
        self.s2_p3_t1 = QtWidgets.QTextEdit(self.s2_page_3)
        self.s2_p3_t1.setGeometry(QtCore.QRect(0, 100, 521, 401))
        self.s2_p3_t1.setObjectName("s2_p3_t1")
        self.stackedWidget_2.addWidget(self.s2_page_3)
        self.code = QtWidgets.QComboBox(self.page_1)
        self.code.setGeometry(QtCore.QRect(0, 0, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.code.setFont(font)
        self.code.setEditable(False)
        self.code.setObjectName("code")
        self.code.addItem("")
        self.code.addItem("")
        self.code.addItem("")
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.tabWidget = QtWidgets.QTabWidget(self.page_2)
        self.tabWidget.setGeometry(QtCore.QRect(0, 10, 1191, 641))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.webView_1 = QtWebKitWidgets.QWebView(self.tab_1)
        self.webView_1.setGeometry(QtCore.QRect(0, 0, 1191, 641))
        self.webView_1.setUrl(QtCore.QUrl("about:blank"))
        self.webView_1.setObjectName("webView_1")
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.webView_2 = QtWebKitWidgets.QWebView(self.tab_2)
        self.webView_2.setGeometry(QtCore.QRect(-1, -1, 1191, 641))
        self.webView_2.setUrl(QtCore.QUrl("about:blank"))
        self.webView_2.setObjectName("webView_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.webView_3 = QtWebKitWidgets.QWebView(self.tab_3)
        self.webView_3.setGeometry(QtCore.QRect(-1, -1, 1191, 641))
        self.webView_3.setUrl(QtCore.QUrl("about:blank"))
        self.webView_3.setObjectName("webView_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.p3_l1 = QtWidgets.QLineEdit(self.page_3)
        self.p3_l1.setGeometry(QtCore.QRect(0, 10, 1191, 41))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.p3_l1.setFont(font)
        self.p3_l1.setObjectName("p3_l1")
        self.p3_b1 = QtWidgets.QPushButton(self.page_3)
        self.p3_b1.setGeometry(QtCore.QRect(0, 70, 111, 41))
        self.p3_b1.setObjectName("p3_b1")
        self.p3_t1 = QtWidgets.QTextEdit(self.page_3)
        self.p3_t1.setGeometry(QtCore.QRect(121, 60, 256, 591))
        self.p3_t1.setObjectName("p3_t1")
        self.p3_w1 = QtWebKitWidgets.QWebView(self.page_3)
        self.p3_w1.setGeometry(QtCore.QRect(383, 60, 811, 611))
        self.p3_w1.setUrl(QtCore.QUrl("about:blank"))
        self.p3_w1.setObjectName("p3_w1")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.stackedWidget.addWidget(self.page_6)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.stackedWidget.addWidget(self.page_7)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.stackedWidget.addWidget(self.page_8)
        self.b1 = QtWidgets.QPushButton(Form)
        self.b1.setGeometry(QtCore.QRect(0, 0, 111, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b1.sizePolicy().hasHeightForWidth())
        self.b1.setSizePolicy(sizePolicy)
        self.b1.setObjectName("b1")
        self.b2 = QtWidgets.QPushButton(Form)
        self.b2.setGeometry(QtCore.QRect(110, 0, 111, 41))
        self.b2.setObjectName("b2")
        self.b3 = QtWidgets.QPushButton(Form)
        self.b3.setGeometry(QtCore.QRect(220, 0, 111, 41))
        self.b3.setObjectName("b3")
        self.b4 = QtWidgets.QPushButton(Form)
        self.b4.setGeometry(QtCore.QRect(330, 0, 111, 41))
        self.b4.setObjectName("b4")
        self.b5 = QtWidgets.QPushButton(Form)
        self.b5.setGeometry(QtCore.QRect(440, 0, 111, 41))
        self.b5.setObjectName("b5")
        self.b6 = QtWidgets.QPushButton(Form)
        self.b6.setGeometry(QtCore.QRect(550, 0, 111, 41))
        self.b6.setObjectName("b6")
        self.b7 = QtWidgets.QPushButton(Form)
        self.b7.setGeometry(QtCore.QRect(660, 0, 111, 41))
        self.b7.setObjectName("b7")
        self.b8 = QtWidgets.QPushButton(Form)
        self.b8.setGeometry(QtCore.QRect(760, 0, 111, 41))
        self.b8.setObjectName("b8")

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(2)
        self.stackedWidget_2.setCurrentIndex(2)
        self.code.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Tools"))
        self.s2_p1_b2.setText(_translate("Form", "urldecode"))
        self.s2_p1_b1.setText(_translate("Form", "urlencode"))
        self.s2_p1_t1.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'宋体\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.s2_p2_b1.setText(_translate("Form", "urlencode"))
        self.s2_p2_b2.setText(_translate("Form", "urldecode"))
        self.s2_p2_t1.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'宋体\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.s2_p3_b1.setText(_translate("Form", "urlencode"))
        self.s2_p3_b2.setText(_translate("Form", "urldecode"))
        self.s2_p3_t1.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'宋体\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.code.setCurrentText(_translate("Form", "url"))
        self.code.setItemText(0, _translate("Form", "url"))
        self.code.setItemText(1, _translate("Form", "base64"))
        self.code.setItemText(2, _translate("Form", "hex"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("Form", "www.aizhan.com"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "tool.chinaz.com"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "www.alexa.cn"))
        self.p3_l1.setText(_translate("Form", "INPUT HASH HERE"))
        self.p3_b1.setText(_translate("Form", "check"))
        self.b1.setText(_translate("Form", "(en|de)code"))
        self.b2.setText(_translate("Form", "toolsites"))
        self.b3.setText(_translate("Form", "(en|de)crypt"))
        self.b4.setText(_translate("Form", "4"))
        self.b5.setText(_translate("Form", "5"))
        self.b6.setText(_translate("Form", "6"))
        self.b7.setText(_translate("Form", "7"))
        self.b8.setText(_translate("Form", "8"))

from PyQt5 import QtWebKitWidgets

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

